// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.25.1
// source: ecomm-grpc/proto/claude/claude.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	IELTSService_EvaluateIELTS_FullMethodName = "/claude.IELTSService/EvaluateIELTS"
)

// IELTSServiceClient is the client API for IELTSService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IELTSServiceClient interface {
	EvaluateIELTS(ctx context.Context, in *EvaluationResponseFromToDataBase, opts ...grpc.CallOption) (*EvaluationResponseFromToDataBase, error)
}

type iELTSServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewIELTSServiceClient(cc grpc.ClientConnInterface) IELTSServiceClient {
	return &iELTSServiceClient{cc}
}

func (c *iELTSServiceClient) EvaluateIELTS(ctx context.Context, in *EvaluationResponseFromToDataBase, opts ...grpc.CallOption) (*EvaluationResponseFromToDataBase, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EvaluationResponseFromToDataBase)
	err := c.cc.Invoke(ctx, IELTSService_EvaluateIELTS_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IELTSServiceServer is the server API for IELTSService service.
// All implementations must embed UnimplementedIELTSServiceServer
// for forward compatibility.
type IELTSServiceServer interface {
	EvaluateIELTS(context.Context, *EvaluationResponseFromToDataBase) (*EvaluationResponseFromToDataBase, error)
	mustEmbedUnimplementedIELTSServiceServer()
}

// UnimplementedIELTSServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIELTSServiceServer struct{}

func (UnimplementedIELTSServiceServer) EvaluateIELTS(context.Context, *EvaluationResponseFromToDataBase) (*EvaluationResponseFromToDataBase, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EvaluateIELTS not implemented")
}
func (UnimplementedIELTSServiceServer) mustEmbedUnimplementedIELTSServiceServer() {}
func (UnimplementedIELTSServiceServer) testEmbeddedByValue()                      {}

// UnsafeIELTSServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IELTSServiceServer will
// result in compilation errors.
type UnsafeIELTSServiceServer interface {
	mustEmbedUnimplementedIELTSServiceServer()
}

func RegisterIELTSServiceServer(s grpc.ServiceRegistrar, srv IELTSServiceServer) {
	// If the following call pancis, it indicates UnimplementedIELTSServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&IELTSService_ServiceDesc, srv)
}

func _IELTSService_EvaluateIELTS_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EvaluationResponseFromToDataBase)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IELTSServiceServer).EvaluateIELTS(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IELTSService_EvaluateIELTS_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IELTSServiceServer).EvaluateIELTS(ctx, req.(*EvaluationResponseFromToDataBase))
	}
	return interceptor(ctx, in, info, handler)
}

// IELTSService_ServiceDesc is the grpc.ServiceDesc for IELTSService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IELTSService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "claude.IELTSService",
	HandlerType: (*IELTSServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "EvaluateIELTS",
			Handler:    _IELTSService_EvaluateIELTS_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ecomm-grpc/proto/claude/claude.proto",
}
