import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ExampleDialog from "./(route)/(landingpage)/landingpage_dialog/landdingpage_dialog";
import { ThemeProvider } from "@/provider/theme-provider";
import { MainNav } from "@/components/navbar/navbar";
import IeltsNavBar from "@/components/ieltsNavbar/ieltsNavbar";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <IeltsNavBar />

          <ExampleDialog />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
