# Use the official PostgreSQL image as the base
FROM postgres:15-alpine

# Set environment variables (adjust as needed)
ENV POSTGRES_DB mydatabase
ENV POSTGRES_USER myuser
ENV POSTGRES_PASSWORD mypassword

# Create a PostgreSQL data directory and grant permissions


# Expose the PostgreSQL port
EXPOSE 5432

# Set the command to start PostgreSQL

CMD ["postgres"]
